// Generated by Scripts/sync-identity.mjs from Config/AppIdentity.json.
import Foundation

enum AppIdentity {
    static let name = "RingCast"
    static let author = "awkj"
    static let bundleIdentifier = "io.github.awkj.ringcast"
    static let developmentBundleIdentifier = "io.github.awkj.ringcast.dev"
    static let betaBundleIdentifier = "io.github.awkj.ringcast.beta"
    static let slug = "ringcast"
    static let urlScheme = "ringcast"
    static let backupExtension = "ringcast"
    static let updatesEnabled = false
    static let updateRepository: String? = nil
    static let repository = "awkj/ringcast"
    static let repositoryURL = URL(string: "https://github.com/\(repository)")!
}
